services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
      - 9229:9229 # for debugging
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=5000
    command: npm run dev:docker

  # frontend:
  # database:
