import { type NextPage } from "next";
import Head from "next/head";
import { Bars3Icon } from "@heroicons/react/24/solid";
import Header from "~/common/components/Header";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen w-screen bg-surface-600"></main>
    </>
  );
};

export default Home;
